# build and deploy generator to github pages and to 
name: Build and Deploy to GHpages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_to_gh_pages:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1

  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Build and Deploy

    steps:
      - uses: actions/checkout@v2

      - run: npm i
      - run: npm ci
      - run: PUBLIC_URL=${{ secrets.PUBLIC_URL }} npm run build
      
      - name: Publish
        if: github.event_name == 'push'
        uses: nogsantos/scp-deploy@v1.3.0
        with:
          src: ./build/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}